export const LARGE_CAP_STOCKS = [
  "RELIANCE", "HDFCBANK", "TCS", "BHARTIARTL", "ICICIBANK", "INFY", "SBIN", "HINDUNILVR", "BAJFINANCE", "ITC", 
  "LICI", "LT", "HCLTECH", "SUNPHARMA", "KOTAKBANK", "MARUTI", "M&M", "AXISBANK", "ULTRACEMCO", "NTPC", 
  "ONGC", "BAJAJFINSV", "TITAN", "WIPRO", "HAL", "ADANIENT", "POWERGRID", "ADANIPORTS", "DMART", 
  "JSWSTEEL", "COALINDIA", "BAJAJ-AUTO", "BEL", "ETERNAL", "NESTLEIND", "ASIANPAINT", "ADANIPOWER", "TRENT", "INDIGO", 
  "IOC", "HINDZINC", "DLF", "TATASTEEL", "VBL", "IRFC", "GRASIM", "VEDL", "JIOFIN", "DIVISLAB", 
  "SBILIFE", "TECHM", "ADANIGREEN", "PIDILITIND", "HDFCLIFE", "HYUNDAI", "EICHERMOT", "HINDALCO", "BAJAJHLDNG", 
  "PFC", "AMBUJACEM", "LODHA", "BPCL", "BRITANNIA", "CHOLAFIN", "ABB", "TVSMOTOR", "TATAPOWER", "CIPLA", 
  "GODREJCP", "BANKBARODA", "GAIL", "SHRIRAMFIN", "PNB", "RECLTD", "INDHOTEL", "SIEMENS", "SOLARINDS", "TORNTPHARM", 
  "MAZDOCK", "MAXHEALTH", "UNITDSPR", "SHREECEM", "TATACONSUM", "DRREDDY", "MANKIND", "BAJAJHFL", "ENRIN", "ADANIENSOL", 
  "MOTHERSON", "CGPOWER", "APOLLOHOSP", "HAVELLS", "INDUSTOWER", "UNIONBANK", "NAUKRI", "LUPIN", "ZYDUSLIFE", "JINDALSTEL"
];

export const MIDCAP_STOCKS = [
  "HDFCAMC", "ICICIGI", "MUTHOOTFIN", "DIXON", "NTPCGREEN", "JSWENERGY", "CANBK", "IDBI", "PERSISTENT", "DABUR", 
  "ICICIPRULI", "BOSCHLTD", "MARICO", "POLYCAB", "SWIGGY", "SRF", "GMRAIRPORT", "CUMMINSIND", "NHPC", 
  "SBICARD", "IOB", "HEROMOTOCO", "RVNL", "SUZLON", "HINDPETRO", "POLICYBZR", "BHEL", "OFSS", "BHARTIHEXA", 
  "INDIANB", "WAAREEENER", "TORNTPOWER", "GICRE", "ATGL", "COLPAL", "LLOYDSME", "AUROPHARMA", "OIL", "INDUSINDBK", 
  "GODREJPROP", "PATANJALI", "ASHOKLEY", "IDEA", "ABBOTINDIA", "OBEROIRLTY", "POWERINDIA", "COROMANDEL", "BERGEPAINT", "JSWINFRA", "IRCTC", 
  "ALKEM", "PRESTIGE", "NMDC", "YESBANK", "PHOENIXLTD", "TIINDIA", "BHARATFORG", "UNOMINDA", "SCHAEFFLER", "LINDEINDIA", 
  "COFORGE", "PIIND", "KALYANKJIL", "UBL", "FACT", "SUNDARMFIN", "PAYTM", "BDL", "MRF", "NYKAA", 
  "VMM", "JSL", "FORTIS", "UPL", "ABCAPITAL", "BALKRISIND", "PAGEIND", "BANKINDIA", "LTTS", "MPHASIS", 
  "SUPREMEIND", "SAIL", "FEDERALBNK", "IREDA", "AUBANK", "IDFCFIRSTB", "HEXT", "PETRONET", "GLAXO", "PREMIERENE", 
  "TATACOMM", "GVT&D", "VOLTAS", "JUBLFOOD", "APLAPOLLO", "CONCOR", "MOTILALOFS", "HUDCO", "UCOBANK", "MFSL", 
  "COCHINSHIP", "BIOCON", "GLENMARK", "FLUOROCHEM", "THERMAX", "NAM-INDIA", "360ONE", "LTF", "ITCHOTELS", "JKCEMENT", 
  "MAHABANK", "BLUESTARCO", "ASTRAL", "CENTRALBK", "SJVN", "TATAELXSI", "GODREJIND", "CRISIL", "ESCORTS", "IPCALAB", 
  "ACC", "KPITTECH", "DALBHARAT", "GODFRYPHLP", "AWL", "M&MFIN", "KAYNES", "KPRMILL", "NATIONALUM", "KEI", 
  "AJANTPHARM", "NH", "HONAUT", "3MINDIA", "LAURUSLABS", "CHOLAHLDNG", "AIIL", "NLCINDIA", "EXIDEIND", "RADICO", 
  "LICHSGFIN", "SONACOMS", "MEDANTA", "AIAENG"
];

export const SMALLCAP_STOCKS = [
  "COHANCE", "IRB", "TATATECH", "ENDURANCE", "CDSL", "ITI", "APARINDS", "GILLETTE", "PPLPHARMA", "NIACL", 
  "GODIGIT", "SYNGENE", "APOLLOTYRE", "IKS", "DEEPAKNTR", "IGL", "AEGISVOPAK", "AEGISLOG", "POONAWALLA", "BRIGADE", 
  "NBCC", "JBCHEPHARM", "GLAND", "SUMICHEM", "EMAMILTD", "OLAELEC", "JYOTICNC", "BANDHANBNK", "ASTERDM", "KIMS", 
  "FSL", "SUNTV", "MSUMI", "PNBHOUSING", "STARHEALTH", "POLYMED", "PGEL", "ABREL", "MRPL", "DELHIVERY", 
  "ZFCVINDIA", "HSCL", "WOCKPHARMA", "CHAMBLFERT", "EIHOTEL", "SHYAMMETL", "LALPATHLAB", "AFFLE", "BAYERCROP", "TATACHEM", 
  "CROMPTON", "HINDCOPPER", "GRSE", "NUVAMA", "AMBER", "RAMCOCEM", "INOXWIND", "EMCURE", "KEC", "PFIZER", 
  "TIMKEN", "WELCORP", "FIVESTAR", "PTCIL", "FIRSTCRY", "SAGILITY", "NAVINFLUOR", "DEVYANI", "CESC", "CASTROLIND", 
  "ABSLAMC", "CARBORUNIV", "ANANTRAJ", "KFINTECH", "ERIS", "CAMS", "REDINGTON", "ABLBL", "CONCORDBIO", "ATUL", 
  "ARE&M", "MANAPPURAM", "TRITURBINE", "AADHARHFC", "ONESOURCE", "CHALET", "GSPL", "RPOWER", "KPIL", "IGIL", 
  "KARURVYSYA", "ZENSARTECH", "BIKAJI", "NATCOPHARM", "IRCON", "AFCONS", "CREDITACC", "DCMSHRIRAM", "ASAHIINDIA", "SIGNATURE", 
  "SARDAEN", "BATAINDIA", "BLS", "SCHNEIDER", "IEX", "IIFL", "NEWGEN", "JWL", "NEULANDLAB", "DOMS", 
  "JBMA", "ELGIEQUIP", "DEEPAKFERT", "WHIRLPOOL", "AKZOINDIA", "JINDALSAW", "AARTIIND", "JUBLPHARMA", "CAPLIPOINT", "ANANDRATHI", 
  "APTUS", "ZENTEC", "BLUEDART", "CYIENT", "KAJARIACER", "EIDPARRY", "SAILIFE", "PCBL", "TRIDENT", 
  "ACE", "TBOTEK", "HBLENGINE", "NIVABUPA", "TARIL", "ECLERX", "AAVAS", "FINCABLES", "TEJASNET", "RAINBOW", 
  "UTIAMC", "CLEAN", "CGCL", "INDGN", "SOBHA", "NCC", "GRAVITA", "TECHNOE", "THELEELA", "IFCI", 
  "LTFOODS", "NAVA", "BBTC", "GESHIP", "BLUEJET", "INDIAMART", "ACMESOLAR", "RRKABEL", "VTL", "MGL", 
  "CUB", "WELSPUNLIV", "RKFORGE", "TTML", "CEATLTD", "HFCL", "MINDACORP", "GRANULES", "GPIL", "SPLPETRO", 
  "BSOFT", "ELECON", "DATAPATTNS", "INTELLECT", "SONATSOFTW", "NUVOCO", "RITES", "ATHERENERG", "FORCEMOT", "TITAGARH", 
  "CRAFTSMAN", "KIRLOSENG", "CHOICEIN", "RAILTEL", "RBLBANK", "NSLNISP", "JUBLINGREA", "ZEEL", "LEMONTREE", "J&KBANK", 
  "JMFINANCIL", "BALRAMCHIN", "HOMEFIRST", "JPPOWER", "PARADEEP", "VIJAYA", "SBFC", "ABDL", "ENGINERSIN", "SAMMAANCAP", 
  "SAPPHIRE", "OLECTRA", "SAREGAMA", "NETWEB", "GMDCLTD", "PVRINOX", "USHAMART", "TEGA", "ABFRL", 
  "GRAPHITE", "MAPMYINDIA", "INDIACEM", "RHIM", "GALLANTT", "MMTC", "CANFINHOME", "ACUTAAS", "ANURAS", "CCL", 
  "BELRISE", "SYRMA", "JKTYRE", "CHENNPETRO", "HEG", "SCI", "LATENTVIEW", "HONASA", "GABRIEL", "CARTRADE"
];

export const INDICES = [
  "^NSEI",    // NIFTY 50 (Benchmark)
  "^CNX100",  // NIFTY 100 (Large Cap)
  "^NSMIDCP", // NIFTY MIDCAP 100
  "BSE-SMLCAP.BO",   // BSE SMALLCAP (Equivalent to NIFTY SMALLCAP 100)
];

export const RAW_UNIVERSE = [...LARGE_CAP_STOCKS, ...MIDCAP_STOCKS, ...SMALLCAP_STOCKS, "^NSEI", "^NSEBANK", "^BSESN"];
export const MARKET_UNIVERSE = [...RAW_UNIVERSE, ...INDICES];
export const NIFTY50 = LARGE_CAP_STOCKS;

export function getBenchmarkIndex(symbol: string): string {
  if (LARGE_CAP_STOCKS.includes(symbol)) return "^CNX100";
  if (MIDCAP_STOCKS.includes(symbol)) return "^NSMIDCP";
  if (SMALLCAP_STOCKS.includes(symbol)) return "BSE-SMLCAP.BO";
  return "^NSEI";
}
